jobs:
 - name: aarch64_u16
   type: runSh
 
   runtime:
    nodePool: Arm64

   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16"
             imageTag: master
         script:
            - java -version
            - nodejs --version
            - yarn -version
            - source /usr/local/rvm/scripts/rvm
            - ruby -v
            - python -V
            - pip --version
            - virtualenv --version
            - git --version
            - aws --version
            - eb --version
            - gcloud version
            - kubectl version --client
            - ansible --version
            - pip show boto
            - pip show boto3
            - pip show apache-libcloud
            - pip show azure
            - pip show dopy
            - packer --version
            - jq --version
            - openstack --version
            
                  
 - name: aarch64_u16all
   type: runSh
   
   runtime:
    nodePool: Arm64
   
   steps:
     - IN: aarch64_u16
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16all"
             imageTag: master
         script:
            - shippable_service couchdb start
            - shippable_service couchdb stop
            - shippable_service elasticsearch start
            - shippable_service elasticsearch stop
            - shippable_service memcached start
            - shippable_service memcached stop
            - shippable_service mongodb start
            - shippable_service mongodb stop
            - shippable_service neo4j start
            - shippable_service neo4j stop
            - shippable_service postgres start
            - shippable_service postgres stop
            - shippable_service rabbitmq start
            - shippable_service rabbitmq stop
            - shippable_service redis start
            - shippable_service redis stop
            - shippable_service selenium start
            - shippable_service selenium stop
            - psql --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - elasticsearch --version
            - memcached --version
            - riak version
            - sudo -i -u couchdb /opt/couchdb/bin/couchdb 2>&1 >/dev/null &
            - sleep 5
            - curl http://127.0.0.1:5984/
            - dpkg -s rabbitmq-server | grep  Version
            - redis-server --version
            - mongod --version
            - cassandra -v  
            - /var/lib/neo4j/bin/neo4j version
            
          
