jobs:
 - name: aarch64_u16
   type: runSh
 
   runtime:
    nodePool: Arm64

   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16"
             imageTag: v6.7.4
         script:
            - java -version
            - nodejs --version
            - yarn -version
            - source /usr/local/rvm/scripts/rvm
            - ruby -v
            - python -V
            - pip --version
            - virtualenv --version
            - git --version
            - aws --version
            - eb --version
            - gcloud version
            - kubectl version --client
            - ansible --version
            - pip show boto
            - pip show boto3
            - pip show apache-libcloud
            - pip show azure
            - pip show dopy
            - packer --version
            - jq --version
            - openstack --version
            

            
                  
 - name: aarch64_u16all
   type: runSh
   
   runtime:
    nodePool: Arm64
   
   steps:
     - IN: aarch64_u16
     - TASK:
         runtime:
           options:
             imageName: "drydock/aarch64_u16all"
             imageTag: master
         script:
            - shippable_service couchdb start
            - shippable_service couchdb stop
            - shippable_service elasticsearch start
            - shippable_service elasticsearch stop
            - shippable_service memcached start
            - shippable_service memcached stop
            - shippable_service mongodb start
            - shippable_service mongodb stop
            - shippable_service neo4j start
            - shippable_service neo4j stop
            - shippable_service postgres start
            - shippable_service postgres stop
            - shippable_service rabbitmq start
            - shippable_service rabbitmq stop
            - shippable_service redis start
            - shippable_service redis stop
            - shippable_service selenium start
            - shippable_service selenium stop
            - elasticsearch --version
            - memcached -V
            - mongod --version
            - /var/lib/neo4j/bin/neo4j version
            - psql --version
            - dpkg -s rabbitmq-server | grep Version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.13.0.jar --version
            - sqlite3 --version
            - couchdb -V
            - redis-server --version
            - pip show pycrypto
            
 - name: aarch64_u16servicesCI_runCI
   type: runCI
   steps:
    - IN: aarch64_u16servicesCI_ciRepo
    - IN: aarch64_u16all
  
 - name: pipelineaarch64_u16nodall_runCI
   type: runCI
   steps:
    - IN: pipelineaarch64_u16nodall_ciRepo 
    - IN: aarch64_u16servicesCI_runCI
 
 - name: pipelineaarch64_u16javall_runCI
   type: runCI
   steps:
    - IN: pipelineaarch64_u16javall_ciRepo
    - IN: aarch64_u16servicesCI_runCI
    
 - name: pipelineaarch64_u16pytall_runCI
   type: runCI
   steps:
    - IN: pipelineaarch64_u16pytall_ciRepo
    - IN: aarch64_u16servicesCI_runCI
 
 - name: piplineaarch64_u16cppall_runCI
   type: runCI
   steps:
    - IN: piplineaarch64_u16cppall_ciRepo
    - IN: aarch64_u16servicesCI_runCI

 
    
